apiVersion: v1
kind: Namespace
metadata:
  name: redsky-system
$patch: delete
---
apiVersion: v1
kind: Secret
metadata:
  name: redsky-manager
$patch: delete
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  annotations:
    checksum/config: SECRET_SHA256
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/version: VERSION
    spec:
      containers:
        - name: manager
          imagePullPolicy: PULL_POLICY
