
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /trial-patches
  failurePolicy: Fail
  name: trial-patches.carbonrelay.com
  rules:
  - apiGroups:
    - apps
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - deployments
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /trial-patches
  failurePolicy: Fail
  name: trial-patches.carbonrelay.com
  rules:
  - apiGroups:
    - apps
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - statefulsets
