version: 2
jobs:
  build:
    docker:
      - image: "circleci/golang:1.13"
    steps:
      - setup_remote_docker
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run:
          name: Bootstrap
          command: .circleci/bootstrap.sh
      - run:
          name: Authorize Google Cloud
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud --quiet auth configure-docker
      - run:
          name: Run tests
          command: make test
      - run:
          name: Build tool
          command: make tool
      - run:
          name: Build Docker images
          command: make docker-build
      - run:
          name: Push Docker images
          command: |
            make docker-push
            DOCKER_TAG=${CIRCLE_TAG:+latest}
            DOCKER_TAG=${DOCKER_TAG:-canary}
            docker tag "${IMG}" "${IMG%%:*}:${DOCKER_TAG}"
            docker push "${IMG%%:*}:${DOCKER_TAG}"
            docker tag "${REDSKYCTL_IMG}" "${REDSKYCTL_IMG%%:*}:${DOCKER_TAG}"
            docker push "${REDSKYCTL_IMG%%:*}:${DOCKER_TAG}"
            docker tag "${SETUPTOOLS_IMG}" "${SETUPTOOLS_IMG%%:*}:${DOCKER_TAG}"
            docker push "${SETUPTOOLS_IMG%%:*}:${DOCKER_TAG}"
      - run:
          name: Prepare artifacts
          command: |
            mkdir dist
            for f in bin/* ; do tar --create --file "dist/$(basename $f).tar.gz" --gzip --transform 's,-.*,,;s,.*/,,' "$f" ; done
            sha256sum dist/* | tee dist/checksums.txt
      - store_artifacts:
          path: dist/redskyctl-darwin-amd64.tar.gz
          destination: redskyctl-darwin-amd64.tar.gz
      - store_artifacts:
          path: dist/redskyctl-linux-amd64.tar.gz
          destination: redskyctl-linux-amd64.tar.gz
      - store_artifacts:
          path: dist/checksums.txt
          destination: checksums.txt
      - run:
          name: Create release
          command: |
            if [[ -n "${CIRCLE_TAG:-}" ]]; then
              ghr -draft -body "$(cat .circleci/RELEASE_TEMPLATE.md)" -name "${CIRCLE_TAG}" "${CIRCLE_TAG}" dist
            else
              echo "Skipping, no tag to release"
            fi
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
workflows:
  version: 2
  dev-build:
    jobs:
      - build:
          context: redskyops
          filters:
            branches:
              only: master
  release-build:
    jobs:
      - build:
          context: redskyops
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
