version: 2
jobs:
  build:
    working_directory: /go/src/github.com/gramLabs/okeanos
    docker:
      - image: "circleci/golang:1.12.5"
    steps:
      - checkout
      - run:
          name: Install kubebuilder
          command: |
            version=1.0.8
            arch=amd64
            curl -L -O https://github.com/kubernetes-sigs/kubebuilder/releases/download/v${version}/kubebuilder_${version}_linux_${arch}.tar.gz
            tar -zxvf kubebuilder_${version}_linux_${arch}.tar.gz
            mv kubebuilder_${version}_linux_${arch} kubebuilder && sudo mv kubebuilder /usr/local/
            export PATH=$PATH:/usr/local/kubebuilder/bin
      - run:
          name: Run tests
          command: make test
      - run:
          name: Build manager binary
          command: make manager
workflows:
  version: 2
  build:
    jobs:
      - build
