version: 2
jobs:
  build:
    working_directory: /go/src/github.com/gramLabs/cordelia
    docker:
      - image: "circleci/golang:1.12.5"
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: Bootstrap
          command: .circleci/bootstrap.sh
      - run:
          name: Run tests
          command: make test
      - run:
          name: Build manager binary
          command: make manager
      - run:
          name: Docker Build
          command: make docker-build
      - run:
          name: Docker Push
          command: make docker-push
      - run:
          # This MUST run AFTER `make docker-build` or the manager image name will be wrong
          # This MUST run AFTER `make docker-push` or we may build a CLI that references non-existent images
          name: Build Tool
          command: make tool_all
      - run:
          name: Docker Tag Latest
          command: |
            docker tag "${IMG}" "${IMG%%:*}:latest"
            docker push "${IMG%%:*}:latest"
            docker tag "${SETUPTOOLS_IMG}" "${SETUPTOOLS_IMG%%:*}:latest"
            docker push "${SETUPTOOLS_IMG%%:*}:latest"
      - store_artifacts:
          path: bin/cordelia-darwin-amd64
      - store_artifacts:
          path: bin/cordelia-linux-amd64
workflows:
  version: 2
  dev-build:
    jobs:
      - build:
          context: carbon-relay-dev
          filters:
            branches:
              only: master
  release-build:
    jobs:
      - build:
          context: carbon-relay-oss
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
