version: 2
jobs:
  build:
    docker:
      - image: "circleci/golang:1.12.5"
    working_directory: /go/src/github.com/gramLabs/okeanos
    steps:
      - checkout
      - run: make
workflows:
  version: 2
  build:
    jobs:
      - build
