apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./service-account.yaml

configMapGenerator:
- name: logstash
  files:
  - ./config/logstash_values.yaml
- name: monitoring
  files:
  - ./config/kube-state-metrics.yaml
  - ./config/prometheus.yaml
  - ./config/cost-model.yaml
  - ./config/node-exporter.yaml

generatorOptions:
  disableNameSuffixHash: true
