
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - batch
  - extensions
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - batch
  - extensions
  resources:
  - jobs/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - apps
  - extensions
  resources:
  - deployments
  - statefulsets
  verbs:
  - get
  - list
  - patch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - list
- apiGroups:
  - redsky.carbonrelay.com
  resources:
  - trials
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - redsky.carbonrelay.com
  resources:
  - trials/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - redsky.carbonrelay.com
  resources:
  - experiments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - redsky.carbonrelay.com
  resources:
  - experiments/status
  verbs:
  - get
  - update
  - patch
