apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-manager
  labels:
    app.kubernetes.io/name: redskyops
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
type: Opaque
data:
  REDSKY_ADDRESS: {{ .Values.address | b64enc | quote }}
  REDSKY_OAUTH2_CLIENT_ID: {{ .Values.oauth2ClientID | b64enc | quote }}
  REDSKY_OAUTH2_CLIENT_SECRET: {{ .Values.oauth2ClientSecret | b64enc | quote }}
  REDSKY_OAUTH2_TOKEN_URL: {{ .Values.oauth2TokenURL | b64enc | quote }}
