apiVersion: v1
kind: Secret
metadata:
  name: client-config
type: Opaque
data:
  client.yaml: |-
    address: {{ .Values.address | quote }}
    oauth2:
      client_id: {{ .Values.oauth2ClientID | quote }}
      client_secret: {{ .Values.oauth2ClientSecret | quote }}
      token_url: {{ .Values.oauth2TokenURL | quote }}
