apiVersion: redskyops.dev/v1alpha1
kind: Experiment
metadata:
  name: simple
spec:
  parameters:
    - name: batchSize
      min: 128
      max: 1024
    - name: workers
      min: 1
      max: 10
  metrics:
    - name: time
      minimize: true
      query: "{{duration .StartTime .CompletionTime}}"
  template: # trial
    spec:
      template: # job
        spec:
          template: # pod
            spec:
              containers:
                - name: benchmark-cli
                  # This image is built from /examples/simple/benchmark-cli
                  image: gcr.io/redskyops/benchmark-cli:6.7.0
                  envFrom:
                    - configMapRef:
                        name: logstash-benchmark
  patches:
    - type: json
      targetRef:
        kind: ConfigMap
        name: logstash-benchmark
      patch: |
        [
          { "op": "replace", "path": "/data/BATCH_SIZE", "value": "{{.Values.batchSize}}" },
          { "op": "replace", "path": "/data/WORKERS", "value": "{{.Values.workers}}" }
        ]
